package babaisyou;

import java.io.IOException;
import java.util.TreeMap;
import java.util.logging.Logger;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * ab
 * @author scien
 */
public class MainWindow extends javax.swing.JFrame {
    
    private TreeMap<String,Level> LevelList;
    private String currentLevel = "";
    
    private LevelBuilder levelbuilder;
    private Level level;
    
    /**
     * Creates new form MainWindow
     * @throws java.io.IOException
     */
    public MainWindow() throws IOException {
        this.LevelList = new TreeMap<>();
        
        Level lev = new Level(35,20);
        
        lev.addBlock(Block.text_BABA, 1, 1);
        lev.addBlock(Block.text_IS, 2, 1);
        lev.addBlock(Block.text_YOU, 3, 1);
        lev.addBlock(Block.object_BABA, 2, 3);
        
        LevelList.put("00", lev);
                
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        panelGame = new javax.swing.JPanel();
        button_left = new javax.swing.JButton();
        button_right = new javax.swing.JButton();
        button_down = new javax.swing.JButton();
        button_up = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1258, 730));
        setResizable(false);
        setSize(new java.awt.Dimension(1258, 730));

        button_left.setText("LEFT");

        button_right.setText("RIGHT");
        button_right.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                button_rightActionPerformed(evt);
            }
        });

        button_down.setText("DOWN");

        button_up.setText("UP");

        javax.swing.GroupLayout panelGameLayout = new javax.swing.GroupLayout(panelGame);
        panelGame.setLayout(panelGameLayout);
        panelGameLayout.setHorizontalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(button_left)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(button_right)
                .addGap(236, 236, 236))
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(button_down)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGameLayout.createSequentialGroup()
                    .addGap(315, 315, 315)
                    .addComponent(button_up)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );
        panelGameLayout.setVerticalGroup(
            panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGameLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_left)
                    .addComponent(button_right))
                .addGap(79, 79, 79)
                .addComponent(button_down)
                .addContainerGap(363, Short.MAX_VALUE))
            .addGroup(panelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGameLayout.createSequentialGroup()
                    .addGap(156, 156, 156)
                    .addComponent(button_up)
                    .addContainerGap(539, Short.MAX_VALUE)))
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            jButton1.setBounds(-10, -10, 1, 1);
            runGame();
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Level lev = openFile();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*
        Level lev = new Level("Level-00",35,20);
        
        lev.addBlock(Block.text_BABA, 1, 1);
        lev.addBlock(Block.text_IS, 2, 1);
        lev.addBlock(Block.text_YOU, 3, 1);
        lev.addBlock(Block.object_BABA, 2, 3);
        
        saveFile(lev);
        */
    }//GEN-LAST:event_jButton3ActionPerformed

    private void button_rightActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_button_rightActionPerformed
    {//GEN-HEADEREND:event_button_rightActionPerformed
        move2( "right" );
    }//GEN-LAST:event_button_rightActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new MainWindow().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_down;
    private javax.swing.JButton button_left;
    private javax.swing.JButton button_right;
    private javax.swing.JButton button_up;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel panelGame;
    // End of variables declaration//GEN-END:variables

    private void runGame() throws IOException {

        levelbuilder = new LevelBuilder();
        
        level = LevelList.get("00");
        currentLevel = "00";
        
        levelbuilder.paint(panelGame.getGraphics(), level);
        
        

    }
    
    private void move(KeyEvent e)
    {
        Mover m = new Mover();
        
        int key = e.getKeyCode();
        
        if (key == KeyEvent.VK_LEFT || key == KeyEvent.VK_A)
            m.moveLeft(LevelList, currentLevel);
    }
    private Level openFile()
    {
        File currentFile = null;
        Level lev = null;
        try {
            JFileChooser jfc = new JFileChooser();
            File file;
            jfc.addChoosableFileFilter(new FileNameExtensionFilter("BabaIsYou Level", "baba"));
            jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            jfc.setCurrentDirectory(new File("C:\\Users\\scien\\Desktop\\"));
            if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
            {
                currentFile = jfc.getSelectedFile();
                FileInputStream fis = new FileInputStream(currentFile);
                ObjectInputStream ois = new ObjectInputStream(fis);

                lev = (Level) ois.readObject();
                
            }
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "File was missing or obstructed.", "ERROR: FILE NOT FOUND", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "IO Exception", "ERROR: FFILE OPEN FAILED", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Class was missing or obstructed.", "ERROR: CLASS NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
        
        return lev;
    }
    
    private void saveFile(Level lev)
    {
        
        JFileChooser jfc = new JFileChooser();
        File file = new File("C:\\Users\\scien\\Desktop\\" + "BROKEN" + ".baba\\"); // orig lev.getName() 
        jfc.setCurrentDirectory(file);

        
        try {
            
            if(jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
            {
                FileOutputStream fos = new FileOutputStream(file);
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(lev);
                oos.close();
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void move2(String dir)
    {
        Mover m = new Mover();
        
        if ( dir.equals( "right" ) )
            m.moveRight(LevelList, currentLevel);
        
        level.setMap( m.getMap() );
        
        levelbuilder.paint( panelGame.getGraphics(), level );
    }
}
